### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by igr** [rockthejvm/udemy-scala-advanced#1]
In https://github.com/rockthejvm/udemy-scala-advanced/blob/master/src/main/scala/lectures/part4implicits/Givens.scala#L61

```
  given listOrdering_v2[A](using simpleOrdering: Ordering[A]), combinator: Combinator[A]): Ordering[List[A]] with {
```

you have an extra `)` before `combinator`.

**Comment by daniel-ciocirlan** [comment]
Done!
